import {Poppins} from "next/font/google"
import "./globals.css";
import Navbar from "./components/navbar";
import { getAuthSession } from "@/utils/auth";
import { Toaster } from "@/components/ui/toaster";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins=Poppins({
  weight:['400','500','600','700','800'],
  subsets:['latin']
})

export default async function RootLayout({ children }) {
  const session =await getAuthSession()
  return (
    <html lang="en" className="">
      <body
        className={`${poppins.className} antialiased`}
      >
        <Navbar/>
        {children}
        <Toaster/>
      </body>
    </html>
  );
}
